name: hand_detection
description: Hand & landmark detection using on-device TFLite models.
version: 1.0.0

repository: "https://github.com/hugocornellier/hand_detection"
homepage: "https://github.com/hugocornellier/hand_detection"

topics:
  - tflite
  - hand-detection
  - computer-vision
  - flutter-plugin

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  opencv_dart: ^2.1.0
  flutter_litert: ^1.0.2
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/models/hand_detection.tflite
    - assets/models/hand_landmark_full.tflite
    - assets/models/gesture_embedder.tflite
    - assets/models/canned_gesture_classifier.tflite
    - assets/samples/2-hands.png
    - assets/samples/two-palms.png
    - assets/samples/img-standing.png
    - assets/samples/istockphoto-462908027-612x612.jpg
    - assets/samples/360_F_554788951_fLAy5C8e9bha4caBTWVJN6rvTD0pEVfE.jpg

  plugin:
    platforms:
      ios:
        dartPluginClass: HandDetectionDart
      android:
        dartPluginClass: HandDetectionDart
      macos:
        pluginClass: HandDetectionPlugin
      windows:
        pluginClass: HandDetectionPlugin
      linux:
        pluginClass: HandDetectionPlugin
